name: Workflow 2

# on:
#   pull_request:
#     branches:
#       - dev  # Adjust branch as per your requirements

on:
  workflow_dispatch:  # Manual trigger
  # push:
  #   branches:
  #     - dev
  # pull_request:
  #    branches:
  #     - dev 

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check for lock file
  #       run: |
  #         if [ -f lock ]; then
  #           echo "Lock file found, waiting for it to be released."
  #           exit 1
  #         else
  #           echo "No lock file found, proceeding."
  #           touch lock
  #         fi      

  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 2 - Job 1"
          sleep 40 
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 2 - Job 2"

      # - name: Remove lock file
      #   run: |
      #     if [ -f lock ]; then
      #       rm lock  # Remove the lock file if it exists
      #     else
      #       echo "No lock file to remove."
      #     fi
