name: Workflow 3

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: pwsh
        run: |
         echo "This is Workflow 3 - Job 1"
         Start-Sleep -s 5

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 3 - Job 2"
